#!/bin/bash

if [ $# -eq 0 ]
then
    echo "Usage: scripts/copy-project <full-path-to-new-project>"
    exit 1
fi

echo "Creating new project at $1"
mkdir -p "$1"

if [ "$(ls -A "$1")" ]; then
    echo "Directory at $1 is not empty, cowardly refusing to create new project."
    exit 1
fi

echo "rsync-ing files to $1"
rsync -avh --exclude=".git" --exclude="node_modules" --exclude=".next" ./ "$1"

echo "Initializing new git repo at $1"
cd "$1" || exit 1
git init
git add .
git commit -m "Initial commit; copied from original project"